#!/usr/bin/env bash


# This data was generated by manually pointing and clicking through imagery. Fun!


for REEF in belize hawaii heron karimunjawa moorea; do
  if [[ ! -d ../data/${REEF}/clean ]]; then
    mkdir ../data/${REEF}/clean
  fi

  rclone copy -v remote:imagery/gcrmn/${REEF}/clean/boundaries.* ../data/${REEF}/clean/
done
